from time import  sleep
def start():
    name="Birthday person"
    print("\t\tWISHING")
    sleep(1)
    print("\t\tYOU ")
    sleep(1)
    print("\t\t ")
    sleep(1)
    print("\t :------------------:")
    sleep(1)
    print("\t ▐█░█▌█▀▀█ █▀▀█ █▀▀█ █▌▄█")
    sleep(1)
    print("\t ▐█▀█▌█▄▄█ █▄▄█ █▄▄█ █▄██")
    sleep(1)
    print('\t ▐█░█▌█▌▐█ █▌░░ █▌░░ ░██')
    sleep(1)
    print('────────???.•°”˜˜”°•.???')
    sleep(1)
    print('▀██▀▀▄──???.•°”˜˜”°•.???')
    sleep(1)
    print('─██▄▀▄──???.•°”˜˜”°•.???')
    sleep(1)
    print('─██───█─▄──────▄──█───')
    sleep(1)
    print('─██───█─▄─▄─▄─▄█▄─█─▄─')
    sleep(1)
    print('▄██▄▄▀──█─█▀───█──█▀─█')
    sleep(1)
    print('────────█─█────█──█──█')
    sleep(1)
    print('██████║░░▄▄▄▄║▄▄║░▄║♥')
    sleep(1)
    print('███║░██║██║░█║██║░█║♥')
    sleep(1)
    print('███║░██║██║░█║██║░█║♥')
    sleep(1)
    print('███║░██║▀█▄▀█║▀█▄▀█║♥')
    sleep(1)
    print('███║░██║░░░░░░▄░░░█║♥')
    sleep(1)
    print('██████║░░░░░░░▀███▀')
    sleep(1)
    print('')
    sleep(1)
    print('')
    sleep(1)
    print('')

    sleep(2)
    print("A message for you.....")
    sleep(4)

    print("\tMAY GOD BLESS YOU AND YOUR FAMILY\n ALWAYS BE HAPPY AND GOOD HEALTH")
    sleep(5)
    print("one second......")
    print()
    sleep(.3)
    print('────▀██████─────▀─────────────█')
    sleep(.3)
    print('─────▌█───▀─█▄▀─█─▄▀▄─█▄▀█─▄▀▀█─▄▀▀')
    sleep(.3)
    print('─────▌███───█───█─█▀▀─█──█─█─▄█─▀▀█')
    sleep(.3)
    print('─────▌█─────▀───▀──▀▀─▀──▀──▀─▀─▀▀▀')
    sleep(.3)
    print('────▄██▄───█──█─────────────────────')
    sleep(.3)
    print('──────────▀█▀─█▄▀▄─▄▀▄')
    sleep(.3)
    print('───────────█──█──█─█▀▀')
    sleep(.3)
    print('───────────▀──▀──▀──▀▀')
    sleep(.3)
    print('──▄▄─▄▄──────▀██▀▀▄───────────█')
    sleep(.3)
    print('─█░█████──────▌█▄▀▄──▄▀▄─▄▀▀─▀█▀')
    sleep(.3)
    print('─▀█░███▀──────▌█───█─█▀▀─▀▀█──█')
    sleep(.3)
    print('───▀█▀────────▌█───█──▀▀─▀▀▀──▀')
    sleep(.3)

    print('─────────────▄██▄▄▀')
a=input("1.Type : 'MJ' \n 2.PRESS 'ENTER' \n (ELSE TYPE 'QUIT' TO QUIT)\n\n:" )
if (a == 'MJ'):
    start()
else:
    print("TAKE CARE BYE!")
